### ISSUE TITLE
Getting java.util.HashMap$HashIterator error while running this doclet.

### ISSUE THREAD

**Issue by aleakhtar** [ryankennedy/swagger-jaxrs-doclet#18]
I am getting following error while running the doclet through maven.
Maven Command: mvn javadoc:javadoc -X

Error:
[ERROR] java.lang.StackOverflowError
[ERROR] at java.util.HashMap$HashIterator.<init>(HashMap.java:778)
[ERROR] at java.util.HashMap$KeyIterator.<init>(HashMap.java:826)
[ERROR] at java.util.HashMap$KeyIterator.<init>(HashMap.java:826)
[ERROR] at java.util.HashMap.newKeyIterator(HashMap.java:840)
[ERROR] at java.util.HashMap$KeySet.iterator(HashMap.java:874)
[ERROR] at com.yammer.dropwizard.apidocs.ServiceDoclet.parseModels(ServiceDoclet.java:288)
[ERROR] at com.yammer.dropwizard.apidocs.ServiceDoclet.parseModels(ServiceDoclet.java:311)
[ERROR] at com.yammer.dropwizard.apidocs.ServiceDoclet.parseModels(ServiceDoclet.java:311)

Maven Configuration:
<configuration>
<doclet>com.yammer.dropwizard.apidocs.ServiceDoclet</doclet>
<docletArtifact>
<groupId>com.unclehulka</groupId>
<artifactId>swagger-jaxrs-doclet</artifactId>
<version>0.0.1.6-SNAPSHOT</version>
</docletArtifact>
<docletPath>/Users/ali/.m2/repository//com/unclehulka/swagger-jaxrs-doclet/0.0.1.6-SNAPSHOT/swagger-jaxrs-doclet-0.0.1.6-SNAPSHOT.jar</docletPath>
<sourcepath>webservice/src/main/com/scb/bsoi/ows/accounts/endpoint/impl</sourcepath>
<javadocDirectory>doc</javadocDirectory>
<reportOutputDirectory>javadocOutput</reportOutputDirectory>
<useStandardDocletOptions>false</useStandardDocletOptions>
<additionalparam>-apiVersion 1 -docBasePath "http://localhost" -apiBasePath "http://localhost"</additionalparam>
</configuration>

**Comment by ESPNMichaelKidd** [comment]
The doclet is having an issue processing one of your jax-rs parameters or return objects.  If you can figure out why (possibly a hash map?), I'll look into fixing it.
