### ISSUE TITLE
Stackoverflow from bidirectional sub resources

### ISSUE THREAD

**Issue by TuomasKiviaho** [ryankennedy/swagger-jaxrs-doclet#81]
CrossClassApiParser never finishes when sub resources generate net structure instead of the usual tree structure. 

A fix could be to check whether or not subresource is already being parsed before creating subResourceParser

```
[ERROR] javadoc: error - In doclet class com.carma.swagger.doclet.ServiceDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
[ERROR] java.lang.StackOverflowError
[ERROR] at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
[ERROR] at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
[ERROR] at java.io.File.exists(File.java:813)
[ERROR] at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1080)
[ERROR] at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:358)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:191)
[ERROR] at com.carma.swagger.doclet.parser.ParserHelper.isCollection(ParserHelper.java:454)
[ERROR] at com.carma.swagger.doclet.parser.ParserHelper.typeOf(ParserHelper.java:336)
[ERROR] at com.carma.swagger.doclet.parser.ParserHelper.typeOf(ParserHelper.java:385)
[ERROR] at com.carma.swagger.doclet.translator.NameBasedTranslator.typeName(NameBasedTranslator.java:74)
[ERROR] at com.carma.swagger.doclet.translator.NameBasedTranslator.parameterTypeName(NameBasedTranslator.java:48)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator$2.apply(FirstNotNullTranslator.java:62)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator$2.apply(FirstNotNullTranslator.java:59)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator.firstNotNullOf(FirstNotNullTranslator.java:110)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator.parameterTypeName(FirstNotNullTranslator.java:59)
[ERROR] at com.carma.swagger.doclet.parser.ApiMethodParser.generateParameters(ApiMethodParser.java:567)
[ERROR] at com.carma.swagger.doclet.parser.ApiMethodParser.parse(ApiMethodParser.java:175)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:139)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
...
```

**Comment by ryankennedy** [comment]
I'm not actively maintaining this anymore. If you want to see updates, check out the @teamcarma fork.
